version: '3'
services:
  pg:
    image: 'postgres:16.2'
    container_name: "easyshop-postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - easyshop-postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: "easyshop-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - easyshop-pgadmin:/var/lib/pgadmin
    depends_on:
      - pg

volumes:
  easyshop-postgres:
  easyshop-pgadmin: